### ISSUE TITLE
KubeJS-Blood-Magic disables 7, fairly important, default Blood Magic recipes.

### ISSUE THREAD

**Issue by VT-14** [KubeJS-Mods/KubeJS-Blood-Magic#1]
On a fresh instillation with only Blood Magic, KubeJS-Blood-Magic, JEI, and Dependencies, 7 default Blood Magic recipes are disabled.  All are related to the Hellfire Forge, but not all Hellfire Forge recipes are disabled.

All Sentient Tools; nearly essential for gathering Demon Will.
* Sentient Sword:    bloodmagic:soulforge/sentientsword
* Sentient Pickaxe:    bloodmagic:soulforge/sentientpickaxe
* Sentient Axe:    bloodmagic:soulforge/sentientaxe
* Sentient Shovel:    bloodmagic:soulforge/sentientshovel
* Sentient Scythe:    bloodmagic:soulforge/sentientscythe

2 Reagents for crafting Sigils, at least one of which is extremely popular.
* Air Reagent:    bloodmagic:soulforge/reagent_air
* Water Reagent:    bloodmagic:soulforge/reagent_water

Latest.log: https://gist.github.com/VT-14/bc15243369c8eb93c11b87fdf6141d7e
Debug Crash: https://gist.github.com/VT-14/7301b9671ef009f8530625aaa73e1bde

**Comment by Motytheultimate** [comment]
Same Issue for me
I fixed it as a workaround

  const { altar, array, soulforge, arc, alchemytable } = e.recipes.bloodmagic

  soulforge('bloodmagic:soulsword', ['bloodmagic:soulgempetty', 'minecraft:iron_sword']).drain(0.0)
  soulforge('bloodmagic:soulaxe', ['bloodmagic:soulgempetty', 'minecraft:iron_axe']).drain(0.0)
  soulforge('bloodmagic:soulscythe', ['bloodmagic:soulgempetty', 'minecraft:iron_hoe']).drain(0.0)
  soulforge('bloodmagic:soulshovel', ['bloodmagic:soulgempetty', 'minecraft:iron_shovel']).drain(0.0)
  soulforge('bloodmagic:soulpickaxe', ['bloodmagic:soulgempetty', 'minecraft:iron_pickaxe']).drain(0.0)
  soulforge('bloodmagic:reagentwater', ['minecraft:sugar', 'minecraft:water_bucket', 'minecraft:water_bucket']).drain(3.0)
  soulforge('bloodmagic:reagentwater', ['minecraft:ghast_tear', 'forge:feathers', 'forge:feathers']).drain(20.0)

drains are taken from the the blood magic sources: [https://github.com/WayofTime/BloodMagic/blob/1.16.3/src/generated/resources/data/bloodmagic/recipes/soulforge/reagent_air.json](url)

**Comment by VT-14** [comment]
I wrote the issue with version 1.0.1 being used.  I believe it was fixed in 1.0.2.  The issue appears to have been caused by those recipes having null inputs (not using all 4 input slots).

**Comment by Motytheultimate** [comment]
Yep it seems to be fixed in 1.0.2
